//! fwgsl integration example
//!
//! This crate demonstrates using [fwgsl](https://github.com/ubugeeei/fwgsl) as a
//! shader authoring language together with `wgsl-bindgen` for type-safe GPU bindings,
//! including **automatic** extraction of algebraic data types (ADTs) and support for
//! **data-carrying enums** (enums whose variants carry struct payloads).
//!
//! ## What changed from the "hacky" approach
//!
//! Previously the build.rs had to manually construct `WgslEnumDefinition` objects
//! and call `add_custom_enum()`.  Now:
//!
//! 1. `build.rs` injects `// @fwgsl-adt:` annotation comments into the WGSL source
//!    using data extracted automatically from the fwgsl HIR.
//! 2. `wgsl-bindgen` parses those annotations and emits Rust enums **without any
//!    user configuration**.
//!
//! ## Pipeline
//!
//! ```text
//! shaders/scale_bias.fwgsl   — functional helpers
//! shaders/color_compute.fwgsl — simple ADT: data Color = Red | Green | Blue
//! shaders/shape_compute.fwgsl — data-carrying ADT: data Shape = Circle F32 | Rect F32 F32
//!     │  fwgsl compiler + HIR-based annotation injection (build.rs)
//!     ▼
//! WGSL with  `// @fwgsl-adt: Color Red:0 Green:1 Blue:2`
//!            `// @fwgsl-adt: Shape Circle:0:Circle Rect:1:Rect`
//!     │  wgsl-bindgen — auto-detects annotations, no WgslEnumDefinition needed
//!     ▼
//! src/shader_bindings.rs  including:
//!   pub enum Color { Red, Green, Blue }          ← simple #[repr(u32)] enum
//!   pub enum Shape { Circle(Circle), Rect(Rect) } ← data-carrying enum
//! ```

mod shader_bindings;

fn main() {
  use shader_bindings::{Color, Shape};
  use shader_bindings::shape_compute::{Circle, Rect};

  println!("fwgsl → WGSL → wgsl-bindgen integration example (automatic ADT extraction)");
  println!("─────────────────────────────────────────────────────────────────────────────");

  // ── Scale-bias shader ──────────────────────────────────────────────────────────
  let params = shader_bindings::scale_bias_compute::ScaleBiasParams::new(2.0, 0.5);
  println!();
  println!("[scale_bias_compute] ScaleBiasParams (from fwgsl helpers):");
  println!("  scale  = {}", params.scale);
  println!("  bias   = {}", params.bias);
  println!("  workgroup size = {:?}",
    shader_bindings::scale_bias_compute::compute::MAIN_WORKGROUP_SIZE);

  // ── Color enum (simple ADT — automatically extracted) ─────────────────────────
  println!();
  println!("[color_compute] Color — simple ADT, automatically extracted from WGSL annotations:");
  println!("  Annotation in WGSL: `// @fwgsl-adt: Color Red:0 Green:1 Blue:2`");
  println!("  Generated by wgsl-bindgen without any WgslEnumDefinition:");
  for color in [Color::Red, Color::Green, Color::Blue] {
    let tag: u32 = u32::from(color);
    let round_trip = Color::try_from(tag).expect("valid discriminant");
    println!("    {color:?} → u32 discriminant {tag} → {round_trip:?}");
  }

  // ── Shape enum (data-carrying ADT — automatically extracted) ──────────────────
  println!();
  println!("[shape_compute] Shape — data-carrying ADT, automatically extracted:");
  println!("  fwgsl source: `data Shape = Circle F32 | Rect F32 F32`");
  println!("  Annotation in WGSL: `// @fwgsl-adt: Shape Circle:0:Circle Rect:1:Rect`");
  println!("  Generated Rust enum:");
  println!("    pub enum Shape {{ Circle(shape_compute::Circle), Rect(shape_compute::Rect) }}");
  println!();

  // Construct Shape variants using the generated Rust types
  let my_circle = Shape::Circle(Circle::new(3.0));
  let my_rect   = Shape::Rect(Rect::new(4.0, 5.0));

  for shape in [my_circle, my_rect] {
    let tag = shape.tag();
    let description = match shape {
      Shape::Circle(c) => format!("Circle(radius={:.1})", c.field0),
      Shape::Rect(r)   => format!("Rect(width={:.1}, height={:.1})", r.field0, r.field1),
    };
    println!("  {description}  →  tag = {tag}");
  }

  // Build ShapeParams from a Shape enum (mimics what a real GPU submission would do)
  let shape = my_rect;
  let shape_params = match shape {
    Shape::Circle(c) => shader_bindings::shape_compute::ShapeParams::new(shape.tag(), c.field0, 0.0, 0.0),
    Shape::Rect(r)   => shader_bindings::shape_compute::ShapeParams::new(shape.tag(), r.field0, r.field1, 0.0),
  };
  println!();
  println!("  ShapeParams for GPU (tag={}, field0={}, field1={}):",
    shape_params.tag, shape_params.field0, shape_params.field1);
  println!("  → GPU computes area = {} * {} = {}",
    shape_params.field0, shape_params.field1,
    shape_params.field0 * shape_params.field1);

  println!();
  println!("All Rust enums were generated automatically from `// @fwgsl-adt:` annotations");
  println!("injected by build.rs.  No WgslEnumDefinition was specified by the user.");
}

