//! fwgsl integration example
//!
//! This crate demonstrates using [fwgsl](https://github.com/ubugeeei/fwgsl) as a
//! shader authoring language together with `wgsl-bindgen` for type-safe GPU bindings,
//! including support for **algebraic data types** (ADTs) that become Rust enums.
//!
//! ## Pipeline
//!
//! ```text
//! shaders/scale_bias.fwgsl   (fwgsl source — helper functions)
//! shaders/color_compute.fwgsl (fwgsl source — with ADT: `data Color = Red | Green | Blue`)
//!     │
//!     ▼  (fwgsl compiler, invoked from build.rs)
//! WGSL helper functions  +  ADT metadata (Color: Red=0, Green=1, Blue=2)
//!     │
//!     ▼  (combined with hand-written bind group declarations in build.rs)
//! scale_bias_compute.wgsl  +  color_compute.wgsl
//!     │
//!     ▼  (wgsl-bindgen, invoked from build.rs with WgslEnumDefinition for Color)
//! src/shader_bindings.rs   (type-safe Rust bindings including a Rust Color enum)
//! ```
//!
//! The generated `shader_bindings` module provides:
//! - `ScaleBiasParams` / `ColorParams` — Rust structs mirroring WGSL uniform structs
//! - `Color` — a `#[repr(u32)]` Rust enum mirroring the fwgsl ADT
//! - `WgpuBindGroup0` — type-safe bind group helpers for each shader

mod shader_bindings;

fn main() {
  use shader_bindings::Color;

  println!("fwgsl → WGSL → wgsl-bindgen integration example (with ADT enums)");
  println!("──────────────────────────────────────────────────────────────────");

  // ── Scale-bias shader ──────────────────────────────────────────────────────
  let params = shader_bindings::scale_bias_compute::ScaleBiasParams::new(2.0, 0.5);
  println!();
  println!("[scale_bias_compute] ScaleBiasParams from generated bindings:");
  println!("  scale  = {}", params.scale);
  println!("  bias   = {}", params.bias);
  println!(
    "  workgroup size: {:?}",
    shader_bindings::scale_bias_compute::compute::MAIN_WORKGROUP_SIZE
  );

  // ── Color enum (from fwgsl ADT) ────────────────────────────────────────────
  println!();
  println!("[color_compute] Color enum — generated from `data Color = Red | Green | Blue`:");

  // The enum is generated by wgsl-bindgen from ADT metadata extracted by fwgsl.
  for color in [Color::Red, Color::Green, Color::Blue] {
    // From<Color> for u32 — write into a WGSL-compatible uniform buffer field
    let tag: u32 = u32::from(color);
    // TryFrom<u32> — round-trip check
    let round_trip = Color::try_from(tag).expect("valid discriminant");
    println!("  {:?} → discriminant {} → {:?}", color, tag, round_trip);
  }

  println!();
  println!("[color_compute] ColorParams holds the selected color variant as a u32:");
  let color_params = shader_bindings::color_compute::ColorParams::new(Color::Green.into());
  println!("  ColorParams {{ color_tag: {} }}", color_params.color_tag);
  println!("  (Color::Green has discriminant {})", u32::from(Color::Green));
  println!();

  println!("Workgroup size: {:?}",
    shader_bindings::color_compute::compute::MAIN_WORKGROUP_SIZE);

  println!();
  println!("The shaders were written in fwgsl, compiled to WGSL, then processed");
  println!("by wgsl-bindgen — which also emitted the Color Rust enum from the");
  println!("ADT metadata extracted by the fwgsl semantic analyzer.");
}

