// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.22.2
// Changes made to this file will not be saved.
// SourceHash: 285fce4309a9837203a78657240531d5dce8afba4e61b6295c829cb9fad8579e

#![allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
  ShadersScaleBias,
  ShadersColorCompute,
  ShadersShapeCompute,
}
impl ShaderEntry {
  pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
    match self {
      Self::ShadersScaleBias => shaders::scale_bias::create_pipeline_layout(device),
      Self::ShadersColorCompute => shaders::color_compute::create_pipeline_layout(device),
      Self::ShadersShapeCompute => shaders::shape_compute::create_pipeline_layout(device),
    }
  }
  pub fn create_shader_module_embed_source(
    &self,
    device: &wgpu::Device,
  ) -> wgpu::ShaderModule {
    match self {
      Self::ShadersScaleBias => {
        shaders::scale_bias::create_shader_module_embed_source(device)
      }
      Self::ShadersColorCompute => {
        shaders::color_compute::create_shader_module_embed_source(device)
      }
      Self::ShadersShapeCompute => {
        shaders::shape_compute::create_shader_module_embed_source(device)
      }
    }
  }
}
#[doc = r" Rust mirror of the fwgsl algebraic data type (ADT) of the same name."]
#[doc = r""]
#[doc = r" Each variant corresponds to a `u32` constructor tag emitted by the fwgsl compiler."]
#[doc = r" Use [`TryFrom<u32>`] to decode a raw WGSL value and [`From<Self> for u32`] to"]
#[doc = r" write the enum into a WGSL-compatible buffer."]
#[doc = r""]
#[doc = r" This type is automatically generated from a `// @fwgsl-adt:` annotation in the"]
#[doc = r" shader source."]
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Color {
  Red = 0u32,
  Green = 1u32,
  Blue = 2u32,
}
impl ::core::convert::TryFrom<u32> for Color {
  type Error = u32;
  #[inline]
  fn try_from(v: u32) -> ::core::result::Result<Self, u32> {
    match v {
      0u32 => ::core::result::Result::Ok(Self::Red),
      1u32 => ::core::result::Result::Ok(Self::Green),
      2u32 => ::core::result::Result::Ok(Self::Blue),
      other => ::core::result::Result::Err(other),
    }
  }
}
impl ::core::convert::From<Color> for u32 {
  #[inline]
  fn from(e: Color) -> u32 {
    e as u32
  }
}
unsafe impl ::bytemuck::Zeroable for Color {}
#[doc = r" Rust mirror of the fwgsl algebraic data type (ADT) of the same name."]
#[doc = r""]
#[doc = r" Each variant either wraps the WGSL struct holding the constructor's payload or"]
#[doc = r" is a unit variant for tag-only constructors. Call [`Self::tag()`] to obtain the"]
#[doc = r" `u32` discriminant value used in the corresponding WGSL shader code."]
#[doc = r""]
#[doc = r" This type is automatically generated from a `// @fwgsl-adt:` annotation in the"]
#[doc = r" shader source."]
#[derive(Debug, Clone, Copy)]
pub enum Shape {
  Circle(shaders::shape_compute::Circle),
  Rect(shaders::shape_compute::Rect),
}
impl Shape {
  #[doc = r" Returns the `u32` discriminant tag used by fwgsl in the corresponding WGSL shader."]
  #[inline]
  pub fn tag(&self) -> u32 {
    match self {
      Self::Circle(_) => 0u32,
      Self::Rect(_) => 1u32,
    }
  }
}
impl ::core::convert::From<Shape> for shaders::shape_compute::ShapeParams {
  #[doc = r" Convert this enum value into the corresponding WGSL uniform params struct."]
  #[doc = r""]
  #[doc = r" The `tag` field is set to the variant's discriminant. Fields present in"]
  #[doc = r" the variant's payload struct are copied by name; all other fields are zeroed."]
  #[inline]
  fn from(e: Shape) -> Self {
    let __tag = e.tag();
    match e {
      Shape::Circle(__v) => shaders::shape_compute::ShapeParams {
        tag: __tag,
        field0: __v.field0,
        field1: ::core::default::Default::default(),
        _pad: ::core::default::Default::default(),
      },
      Shape::Rect(__v) => shaders::shape_compute::ShapeParams {
        tag: __tag,
        field0: __v.field0,
        field1: __v.field1,
        _pad: ::core::default::Default::default(),
      },
    }
  }
}
mod _root {
  pub use super::*;
  pub trait SetBindGroup {
    fn set_bind_group(
      &mut self,
      index: u32,
      bind_group: &wgpu::BindGroup,
      offsets: &[wgpu::DynamicOffset],
    );
  }
  impl SetBindGroup for wgpu::ComputePass<'_> {
    fn set_bind_group(
      &mut self,
      index: u32,
      bind_group: &wgpu::BindGroup,
      offsets: &[wgpu::DynamicOffset],
    ) {
      self.set_bind_group(index, bind_group, offsets);
    }
  }
}
pub mod layout_asserts {
  use super::{_root, _root::*};
  const WGSL_BASE_TYPE_ASSERTS: () = {};
  const SHADERS_SCALE_BIAS_SCALE_BIAS_PARAMS_ASSERTS: () = {
    assert!(std::mem::offset_of!(shaders::scale_bias::ScaleBiasParams, scale) == 0);
    assert!(std::mem::offset_of!(shaders::scale_bias::ScaleBiasParams, bias) == 4);
    assert!(std::mem::size_of::<shaders::scale_bias::ScaleBiasParams>() == 8);
  };
  const SHADERS_COLOR_COMPUTE_COLOR_PARAMS_ASSERTS: () = {
    assert!(std::mem::offset_of!(shaders::color_compute::ColorParams, color_tag) == 0);
    assert!(std::mem::size_of::<shaders::color_compute::ColorParams>() == 4);
  };
  const SHADERS_SHAPE_COMPUTE_SHAPE_PARAMS_ASSERTS: () = {
    assert!(std::mem::offset_of!(shaders::shape_compute::ShapeParams, tag) == 0);
    assert!(std::mem::offset_of!(shaders::shape_compute::ShapeParams, field0) == 4);
    assert!(std::mem::offset_of!(shaders::shape_compute::ShapeParams, field1) == 8);
    assert!(std::mem::offset_of!(shaders::shape_compute::ShapeParams, _pad) == 12);
    assert!(std::mem::size_of::<shaders::shape_compute::ShapeParams>() == 16);
  };
}
pub mod shaders {
  use super::{_root, _root::*};
  pub mod scale_bias {
    use super::{_root, _root::*};
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct ScaleBiasParams {
      #[doc = "offset: 0, size: 4, type: `f32`"]
      pub scale: f32,
      #[doc = "offset: 4, size: 4, type: `f32`"]
      pub bias: f32,
    }
    impl ScaleBiasParams {
      pub const fn new(scale: f32, bias: f32) -> Self {
        Self { scale, bias }
      }
    }
    pub mod compute {
      use super::{_root, _root::*};
      pub const MAIN_WORKGROUP_SIZE: [u32; 3] = [64, 1, 1];
      pub fn create_main_pipeline_embed_source(
        device: &wgpu::Device,
      ) -> wgpu::ComputePipeline {
        let module = super::create_shader_module_embed_source(device);
        let layout = super::create_pipeline_layout(device);
        device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
          label: Some("Compute Pipeline main"),
          layout: Some(&layout),
          module: &module,
          entry_point: Some("main"),
          compilation_options: Default::default(),
          cache: None,
        })
      }
    }
    pub const ENTRY_MAIN: &str = "main";
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
      pub data: wgpu::BufferBinding<'a>,
      pub params: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
      pub data: wgpu::BindGroupEntry<'a>,
      pub params: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
      pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
        Self {
          data: wgpu::BindGroupEntry {
            binding: 0,
            resource: wgpu::BindingResource::Buffer(params.data),
          },
          params: wgpu::BindGroupEntry {
            binding: 1,
            resource: wgpu::BindingResource::Buffer(params.params),
          },
        }
      }
      pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
        [self.data, self.params]
      }
      pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
        self.into_array().into_iter().collect()
      }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
      pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
        wgpu::BindGroupLayoutDescriptor {
          label: Some("ShadersScaleBias::BindGroup0::LayoutDescriptor"),
          entries: &[
            #[doc = " @binding(0): \"data\""]
            wgpu::BindGroupLayoutEntry {
              binding: 0,
              visibility: wgpu::ShaderStages::COMPUTE,
              ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Storage { read_only: false },
                has_dynamic_offset: false,
                min_binding_size: None,
              },
              count: None,
            },
            #[doc = " @binding(1): \"params\""]
            wgpu::BindGroupLayoutEntry {
              binding: 1,
              visibility: wgpu::ShaderStages::COMPUTE,
              ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                  _root::shaders::scale_bias::ScaleBiasParams,
                >() as _),
              },
              count: None,
            },
          ],
        };
      pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
        device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
      }
      pub fn from_bindings(
        device: &wgpu::Device,
        bindings: WgpuBindGroup0Entries,
      ) -> Self {
        let bind_group_layout = Self::get_bind_group_layout(device);
        let entries = bindings.into_array();
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
          label: Some("ShadersScaleBias::BindGroup0"),
          layout: &bind_group_layout,
          entries: &entries,
        });
        Self(bind_group)
      }
      pub fn set(&self, pass: &mut impl SetBindGroup) {
        pass.set_bind_group(0, &self.0, &[]);
      }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
      pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
      pub fn set(&self, pass: &mut impl SetBindGroup) {
        self.bind_group0.set(pass);
      }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
      pub fn bind_group_layout_entries(
        entries: [wgpu::BindGroupLayout; 1],
      ) -> [wgpu::BindGroupLayout; 1] {
        entries
      }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
      device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some("ShadersScaleBias::PipelineLayout"),
        bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
        immediate_size: 0u32,
      })
    }
    pub fn create_shader_module_embed_source(
      device: &wgpu::Device,
    ) -> wgpu::ShaderModule {
      let source = std::borrow::Cow::Borrowed(SHADER_STRING);
      device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("scale_bias.fwgsl"),
        source: wgpu::ShaderSource::Wgsl(source),
      })
    }
    pub const SHADER_STRING: &str = r#"
struct ScaleBiasParams {
    scale: f32,
    bias: f32,
}

@group(0) @binding(0) 
var<storage, read_write> data: array<f32>;
@group(0) @binding(1) 
var<uniform> params: ScaleBiasParams;

fn scale_val(s: f32, x: f32) -> f32 {
    return (x * s);
}

fn bias_val(b: f32, x_1: f32) -> f32 {
    return (x_1 + b);
}

fn scale_bias(s_1: f32, b_1: f32, x_2: f32) -> f32 {
    return ((x_2 * s_1) + b_1);
}

fn saturate_(x_3: f32) -> f32 {
    var _if_tmp_700_: f32 = 0f;
    var _if_tmp_732_: f32 = 0f;

    if (x_3 > 0f) {
        _if_tmp_700_ = x_3;
    } else {
        _if_tmp_700_ = 0f;
    }
    let a = _if_tmp_700_;
    if (a < 1f) {
        _if_tmp_732_ = a;
    } else {
        _if_tmp_732_ = 1f;
    }
    let _e11 = _if_tmp_732_;
    return _e11;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
    let idx = global_id.x;
    if (idx >= arrayLength((&data))) {
        return;
    }
    let _e9 = params.scale;
    let _e12 = params.bias;
    let _e15 = data[idx];
    let _e16 = scale_bias(_e9, _e12, _e15);
    data[idx] = _e16;
    return;
}
"#;
  }
  pub mod color_compute {
    use super::{_root, _root::*};
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct ColorParams {
      #[doc = "offset: 0, size: 4, type: `u32`"]
      pub color_tag: u32,
    }
    impl ColorParams {
      pub const fn new(color_tag: u32) -> Self {
        Self { color_tag }
      }
    }
    pub mod compute {
      use super::{_root, _root::*};
      pub const MAIN_WORKGROUP_SIZE: [u32; 3] = [1, 1, 1];
      pub fn create_main_pipeline_embed_source(
        device: &wgpu::Device,
      ) -> wgpu::ComputePipeline {
        let module = super::create_shader_module_embed_source(device);
        let layout = super::create_pipeline_layout(device);
        device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
          label: Some("Compute Pipeline main"),
          layout: Some(&layout),
          module: &module,
          entry_point: Some("main"),
          compilation_options: Default::default(),
          cache: None,
        })
      }
    }
    pub const ENTRY_MAIN: &str = "main";
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
      pub output: wgpu::BufferBinding<'a>,
      pub params: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
      pub output: wgpu::BindGroupEntry<'a>,
      pub params: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
      pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
        Self {
          output: wgpu::BindGroupEntry {
            binding: 0,
            resource: wgpu::BindingResource::Buffer(params.output),
          },
          params: wgpu::BindGroupEntry {
            binding: 1,
            resource: wgpu::BindingResource::Buffer(params.params),
          },
        }
      }
      pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
        [self.output, self.params]
      }
      pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
        self.into_array().into_iter().collect()
      }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
      pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
        wgpu::BindGroupLayoutDescriptor {
          label: Some("ShadersColorCompute::BindGroup0::LayoutDescriptor"),
          entries: &[
            #[doc = " @binding(0): \"output\""]
            wgpu::BindGroupLayoutEntry {
              binding: 0,
              visibility: wgpu::ShaderStages::COMPUTE,
              ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Storage { read_only: false },
                has_dynamic_offset: false,
                min_binding_size: std::num::NonZeroU64::new(
                  std::mem::size_of::<[f32; 4]>() as _,
                ),
              },
              count: None,
            },
            #[doc = " @binding(1): \"params\""]
            wgpu::BindGroupLayoutEntry {
              binding: 1,
              visibility: wgpu::ShaderStages::COMPUTE,
              ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                  _root::shaders::color_compute::ColorParams,
                >() as _),
              },
              count: None,
            },
          ],
        };
      pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
        device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
      }
      pub fn from_bindings(
        device: &wgpu::Device,
        bindings: WgpuBindGroup0Entries,
      ) -> Self {
        let bind_group_layout = Self::get_bind_group_layout(device);
        let entries = bindings.into_array();
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
          label: Some("ShadersColorCompute::BindGroup0"),
          layout: &bind_group_layout,
          entries: &entries,
        });
        Self(bind_group)
      }
      pub fn set(&self, pass: &mut impl SetBindGroup) {
        pass.set_bind_group(0, &self.0, &[]);
      }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
      pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
      pub fn set(&self, pass: &mut impl SetBindGroup) {
        self.bind_group0.set(pass);
      }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
      pub fn bind_group_layout_entries(
        entries: [wgpu::BindGroupLayout; 1],
      ) -> [wgpu::BindGroupLayout; 1] {
        entries
      }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
      device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some("ShadersColorCompute::PipelineLayout"),
        bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
        immediate_size: 0u32,
      })
    }
    pub fn create_shader_module_embed_source(
      device: &wgpu::Device,
    ) -> wgpu::ShaderModule {
      let source = std::borrow::Cow::Borrowed(SHADER_STRING);
      device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("color_compute.fwgsl"),
        source: wgpu::ShaderSource::Wgsl(source),
      })
    }
    pub const SHADER_STRING: &str = r#"
struct ColorParams {
    color_tag: u32,
}

@group(0) @binding(0) 
var<storage, read_write> output: array<f32, 4>;
@group(0) @binding(1) 
var<uniform> params: ColorParams;

fn color_to_r(c: u32) -> f32 {
    var _case_tmp_705_: f32 = 0f;

    if (c == 0u) {
        _case_tmp_705_ = 1f;
    } else {
        if (c == 1u) {
            _case_tmp_705_ = 0f;
        } else {
            if (c == 2u) {
                _case_tmp_705_ = 0f;
            }
        }
    }
    let _e12 = _case_tmp_705_;
    return _e12;
}

fn color_to_g(c_1: u32) -> f32 {
    var _case_tmp_806_: f32 = 0f;

    if (c_1 == 0u) {
        _case_tmp_806_ = 0f;
    } else {
        if (c_1 == 1u) {
            _case_tmp_806_ = 1f;
        } else {
            if (c_1 == 2u) {
                _case_tmp_806_ = 0f;
            }
        }
    }
    let _e12 = _case_tmp_806_;
    return _e12;
}

fn color_to_b(c_2: u32) -> f32 {
    var _case_tmp_907_: f32 = 0f;

    if (c_2 == 0u) {
        _case_tmp_907_ = 0f;
    } else {
        if (c_2 == 1u) {
            _case_tmp_907_ = 0f;
        } else {
            if (c_2 == 2u) {
                _case_tmp_907_ = 1f;
            }
        }
    }
    let _e12 = _case_tmp_907_;
    return _e12;
}

@compute @workgroup_size(1, 1, 1) 
fn main(@builtin(global_invocation_id) _global_id: vec3<u32>) {
    let selected_color = params.color_tag;
    let _e5 = color_to_r(selected_color);
    output[0] = _e5;
    let _e8 = color_to_g(selected_color);
    output[1] = _e8;
    let _e11 = color_to_b(selected_color);
    output[2] = _e11;
    output[3] = 1f;
    return;
}
"#;
  }
  pub mod shape_compute {
    use super::{_root, _root::*};
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Circle {
      pub field0: f32,
    }
    impl Circle {
      pub const fn new(field0: f32) -> Self {
        Self { field0 }
      }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Rect {
      pub field0: f32,
      pub field1: f32,
    }
    impl Rect {
      pub const fn new(field0: f32, field1: f32) -> Self {
        Self { field0, field1 }
      }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct ShapeParams {
      #[doc = "offset: 0, size: 4, type: `u32`"]
      pub tag: u32,
      #[doc = "offset: 4, size: 4, type: `f32`"]
      pub field0: f32,
      #[doc = "offset: 8, size: 4, type: `f32`"]
      pub field1: f32,
      #[doc = "offset: 12, size: 4, type: `f32`"]
      pub _pad: f32,
    }
    impl ShapeParams {
      pub const fn new(tag: u32, field0: f32, field1: f32, _pad: f32) -> Self {
        Self {
          tag,
          field0,
          field1,
          _pad,
        }
      }
    }
    pub mod compute {
      use super::{_root, _root::*};
      pub const MAIN_WORKGROUP_SIZE: [u32; 3] = [1, 1, 1];
      pub fn create_main_pipeline_embed_source(
        device: &wgpu::Device,
      ) -> wgpu::ComputePipeline {
        let module = super::create_shader_module_embed_source(device);
        let layout = super::create_pipeline_layout(device);
        device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
          label: Some("Compute Pipeline main"),
          layout: Some(&layout),
          module: &module,
          entry_point: Some("main"),
          compilation_options: Default::default(),
          cache: None,
        })
      }
    }
    pub const ENTRY_MAIN: &str = "main";
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
      pub output: wgpu::BufferBinding<'a>,
      pub params: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
      pub output: wgpu::BindGroupEntry<'a>,
      pub params: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
      pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
        Self {
          output: wgpu::BindGroupEntry {
            binding: 0,
            resource: wgpu::BindingResource::Buffer(params.output),
          },
          params: wgpu::BindGroupEntry {
            binding: 1,
            resource: wgpu::BindingResource::Buffer(params.params),
          },
        }
      }
      pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
        [self.output, self.params]
      }
      pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
        self.into_array().into_iter().collect()
      }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
      pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
        wgpu::BindGroupLayoutDescriptor {
          label: Some("ShadersShapeCompute::BindGroup0::LayoutDescriptor"),
          entries: &[
            #[doc = " @binding(0): \"output\""]
            wgpu::BindGroupLayoutEntry {
              binding: 0,
              visibility: wgpu::ShaderStages::COMPUTE,
              ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Storage { read_only: false },
                has_dynamic_offset: false,
                min_binding_size: std::num::NonZeroU64::new(
                  std::mem::size_of::<[f32; 1]>() as _,
                ),
              },
              count: None,
            },
            #[doc = " @binding(1): \"params\""]
            wgpu::BindGroupLayoutEntry {
              binding: 1,
              visibility: wgpu::ShaderStages::COMPUTE,
              ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                  _root::shaders::shape_compute::ShapeParams,
                >() as _),
              },
              count: None,
            },
          ],
        };
      pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
        device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
      }
      pub fn from_bindings(
        device: &wgpu::Device,
        bindings: WgpuBindGroup0Entries,
      ) -> Self {
        let bind_group_layout = Self::get_bind_group_layout(device);
        let entries = bindings.into_array();
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
          label: Some("ShadersShapeCompute::BindGroup0"),
          layout: &bind_group_layout,
          entries: &entries,
        });
        Self(bind_group)
      }
      pub fn set(&self, pass: &mut impl SetBindGroup) {
        pass.set_bind_group(0, &self.0, &[]);
      }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
      pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
      pub fn set(&self, pass: &mut impl SetBindGroup) {
        self.bind_group0.set(pass);
      }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
      pub fn bind_group_layout_entries(
        entries: [wgpu::BindGroupLayout; 1],
      ) -> [wgpu::BindGroupLayout; 1] {
        entries
      }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
      device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some("ShadersShapeCompute::PipelineLayout"),
        bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
        immediate_size: 0u32,
      })
    }
    pub fn create_shader_module_embed_source(
      device: &wgpu::Device,
    ) -> wgpu::ShaderModule {
      let source = std::borrow::Cow::Borrowed(SHADER_STRING);
      device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("shape_compute.fwgsl"),
        source: wgpu::ShaderSource::Wgsl(source),
      })
    }
    pub const SHADER_STRING: &str = r#"
struct Circle {
    field0_: f32,
}

struct Rect {
    field0_: f32,
    field1_: f32,
}

struct ShapeParams {
    tag: u32,
    field0_: f32,
    field1_: f32,
    _pad: f32,
}

@group(0) @binding(0) 
var<storage, read_write> output: array<f32, 1>;
@group(0) @binding(1) 
var<uniform> params: ShapeParams;

@compute @workgroup_size(1, 1, 1) 
fn main(@builtin(global_invocation_id) _global_id: vec3<u32>) {
    var area: f32 = 0f;

    let _e3 = params.tag;
    if (_e3 == 0u) {
        let _e8 = params.field0_;
        let _e11 = params.field0_;
        area = (_e8 * _e11);
    } else {
        let _e16 = params.field0_;
        let _e19 = params.field1_;
        area = (_e16 * _e19);
    }
    let _e23 = area;
    output[0] = _e23;
    return;
}
"#;
  }
}
pub mod bytemuck_impls {
  use super::{_root, _root::*};
  unsafe impl bytemuck::Zeroable for shaders::scale_bias::ScaleBiasParams {}
  unsafe impl bytemuck::Pod for shaders::scale_bias::ScaleBiasParams {}
  unsafe impl bytemuck::Zeroable for shaders::color_compute::ColorParams {}
  unsafe impl bytemuck::Pod for shaders::color_compute::ColorParams {}
  unsafe impl bytemuck::Zeroable for shaders::shape_compute::Circle {}
  unsafe impl bytemuck::Pod for shaders::shape_compute::Circle {}
  unsafe impl bytemuck::Zeroable for shaders::shape_compute::Rect {}
  unsafe impl bytemuck::Pod for shaders::shape_compute::Rect {}
  unsafe impl bytemuck::Zeroable for shaders::shape_compute::ShapeParams {}
  unsafe impl bytemuck::Pod for shaders::shape_compute::ShapeParams {}
}
