//! Multisampled Texture Demo
//!
//! This demo showcases how to properly use and bind `texture_multisampled_2d<T>`
//! with `wgsl_bindgen`.
//!
//! # Key Features
//! - Demonstrates the fix for `wgsl_bindgen` issue #92 where multisampled float textures
//!   must have `filterable: false` to comply with WebGPU/wgpu validation rules.
//! - Implements a two-pass rendering pipeline:
//!   1. **MSAA Pass**: Renders a dynamically rotating, mouse-tracking RGB triangle
//!      into a 4x multisampled texture.
//!   2. **Resolve Pass**: Reads the multisampled texture in a fullscreen quad shader
//!      (`multisampled_texture_demo.wgsl`), manually resolving the 4 samples and applying
//!      a time-based pulsing effect.
//!
//! By using explicit pipeline layouts generated by `wgsl_bindgen`, we can safely and
//! predictably bind our resources across multiple passes without hitting WGPU validation errors.

use super::Demo;
use crate::shader_bindings;
use std::time::Instant;
use wgpu::util::DeviceExt;

pub struct MultisampledTextureDemo {
  resolve_pipeline: wgpu::RenderPipeline,
  shape_pipeline: wgpu::RenderPipeline,
  bind_group1: shader_bindings::multisampled_texture_demo::WgpuBindGroup1,
  vertex_buffer: wgpu::Buffer,
  msaa_texture: wgpu::Texture,
  msaa_texture_view: wgpu::TextureView,
  start_time: Instant,
  surface_format: wgpu::TextureFormat,
  // Add local global bindings for the offscreen pass
  global_time_buffer: wgpu::Buffer,
  global_bind_group: shader_bindings::global_bindings::WgpuBindGroup0,
}

impl Demo for MultisampledTextureDemo {
  fn new(
    device: &wgpu::Device,
    _queue: &wgpu::Queue,
    surface_format: wgpu::TextureFormat,
  ) -> Self {
    // Create shader and pipeline layout
    let shader =
      shader_bindings::multisampled_texture_demo::create_shader_module_embed_source(device);
    let render_pipeline_layout =
      shader_bindings::multisampled_texture_demo::create_pipeline_layout(device);

    let resolve_pipeline =
      device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some("MultisampledTexture Resolve Pipeline"),
        layout: Some(&render_pipeline_layout),
        vertex: shader_bindings::multisampled_texture_demo::vertex_state(
          &shader,
          &shader_bindings::multisampled_texture_demo::vs_main_entry(
            wgpu::VertexStepMode::Vertex,
          ),
        ),
        fragment: Some(wgpu::FragmentState {
          module: &shader,
          entry_point: Some(shader_bindings::multisampled_texture_demo::ENTRY_FS_MAIN),
          targets: &[Some(surface_format.into())],
          compilation_options: Default::default(),
        }),
        primitive: wgpu::PrimitiveState::default(),
        depth_stencil: None,
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: Default::default(),
      });

    let shape_pipeline_layout_bg =
      shader_bindings::global_bindings::WgpuBindGroup0::get_bind_group_layout(device);
    let shape_pipeline_layout =
      device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some("MultisampledTexture Shape Pipeline Layout"),
        bind_group_layouts: &[Some(&shape_pipeline_layout_bg)],
        immediate_size: 0,
      });

    let shape_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
      label: Some("MultisampledTexture Shape Pipeline"),
      layout: Some(&shape_pipeline_layout),
      vertex: wgpu::VertexState {
        module: &shader,
        entry_point: Some(shader_bindings::multisampled_texture_demo::ENTRY_VS_MSAA),
        buffers: &[], // No buffers, uses vertex_index
        compilation_options: Default::default(),
      },
      fragment: Some(wgpu::FragmentState {
        module: &shader,
        entry_point: Some(shader_bindings::multisampled_texture_demo::ENTRY_FS_MSAA),
        targets: &[Some(wgpu::TextureFormat::Rgba8Unorm.into())],
        compilation_options: Default::default(),
      }),
      primitive: wgpu::PrimitiveState::default(),
      depth_stencil: None,
      multisample: wgpu::MultisampleState {
        count: 4,
        mask: !0,
        alpha_to_coverage_enabled: false,
      },
      multiview_mask: None,
      cache: Default::default(),
    });

    // Create a multisampled texture
    let msaa_texture = device.create_texture(&wgpu::TextureDescriptor {
      label: Some("Multisampled Texture"),
      size: wgpu::Extent3d {
        width: 1024,
        height: 1024,
        depth_or_array_layers: 1,
      },
      mip_level_count: 1,
      sample_count: 4,
      dimension: wgpu::TextureDimension::D2,
      format: wgpu::TextureFormat::Rgba8Unorm,
      usage: wgpu::TextureUsages::TEXTURE_BINDING
        | wgpu::TextureUsages::RENDER_ATTACHMENT,
      view_formats: &[],
    });

    let msaa_texture_view =
      msaa_texture.create_view(&wgpu::TextureViewDescriptor::default());

    // Create bind group
    let bind_group1 =
      shader_bindings::multisampled_texture_demo::WgpuBindGroup1::from_bindings(
        device,
        shader_bindings::multisampled_texture_demo::WgpuBindGroup1Entries::new(
          shader_bindings::multisampled_texture_demo::WgpuBindGroup1EntriesParams {
            ms_texture: &msaa_texture_view,
          },
        ),
      );

    // Fullscreen quad
    let vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
      label: Some("vertex buffer"),
      contents: bytemuck::cast_slice(&[
        glam::vec3(-1.0, -1.0, 0.0),
        glam::vec3(1.0, -1.0, 0.0),
        glam::vec3(-1.0, 1.0, 0.0),
        glam::vec3(1.0, -1.0, 0.0),
        glam::vec3(1.0, 1.0, 0.0),
        glam::vec3(-1.0, 1.0, 0.0),
      ]),
      usage: wgpu::BufferUsages::VERTEX,
    });

    let global_time_buffer =
      device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: Some("msaa local global uniforms buffer"),
        contents: bytemuck::cast_slice(&[
          shader_bindings::global_bindings::GlobalUniforms::new(
            0.0,
            1.0,
            glam::Vec2::new(1024.0, 1024.0),
            glam::Vec2::new(0.0, 0.0),
          ),
        ]),
        usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
      });

    let global_bind_group =
      shader_bindings::global_bindings::WgpuBindGroup0::from_bindings(
        device,
        shader_bindings::global_bindings::WgpuBindGroup0Entries::new(
          shader_bindings::global_bindings::WgpuBindGroup0EntriesParams {
            globals: global_time_buffer.as_entire_buffer_binding(),
          },
        ),
      );

    Self {
      resolve_pipeline,
      shape_pipeline,
      bind_group1,
      vertex_buffer,
      msaa_texture,
      msaa_texture_view,
      start_time: Instant::now(),
      surface_format,
      global_time_buffer,
      global_bind_group,
    }
  }

  fn name(&self) -> &'static str {
    "Multisampled Texture Demo"
  }

  fn description(&self) -> &'static str {
    "Showcases using multisampled textures (MSAA) with manual resolve in WGSL"
  }

  fn update(
    &mut self,
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    context: super::DemoContext,
  ) {
    // Update local global bindings for the offscreen pass
    let global_uniforms = shader_bindings::global_bindings::GlobalUniforms::new(
      context.elapsed_time,
      1.0,
      context.frame_size,
      context.mouse_pos,
    );
    queue.write_buffer(
      &self.global_time_buffer,
      0,
      bytemuck::cast_slice(&[global_uniforms]),
    );

    // Render the spinning triangle into the MSAA texture
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
      label: Some("MSAA Shape Render Encoder"),
    });

    {
      let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
        label: Some("MSAA Shape Render Pass"),
        color_attachments: &[Some(wgpu::RenderPassColorAttachment {
          view: &self.msaa_texture_view,
          depth_slice: None,
          resolve_target: None,
          ops: wgpu::Operations {
            load: wgpu::LoadOp::Clear(wgpu::Color {
              r: 0.05,
              g: 0.05,
              b: 0.05,
              a: 1.0,
            }),
            store: wgpu::StoreOp::Store,
          },
        })],
        depth_stencil_attachment: None,
        timestamp_writes: None,
        occlusion_query_set: None,
        multiview_mask: None,
      });

      rpass.set_pipeline(&self.shape_pipeline);

      // Bind the local global uniforms to group 0
      self.global_bind_group.set(&mut rpass);

      rpass.draw(0..3, 0..1);
    }

    queue.submit(std::iter::once(encoder.finish()));
  }

  fn render<'a>(
    &'a mut self,
    _device: &wgpu::Device,
    render_pass: &mut wgpu::RenderPass<'a>,
  ) {
    render_pass.set_pipeline(&self.resolve_pipeline);

    self.bind_group1.set(render_pass);

    render_pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
    render_pass.draw(0..6, 0..1);
  }

  fn get_pipeline(&self) -> &wgpu::RenderPipeline {
    &self.resolve_pipeline
  }
}
