// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.23.0
// Changes made to this file will not be saved.
// SourceHash: 2bf551c4c3809945c7cf9c0d614411bf95f124985e967ded1a80c41210a1a123

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
  BufferLayouts,
}
impl ShaderEntry {
  pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
    match self {
      Self::BufferLayouts => buffer_layouts::create_pipeline_layout(device),
    }
  }
  pub fn create_shader_module_embed_source(
    &self,
    device: &wgpu::Device,
  ) -> wgpu::ShaderModule {
    match self {
      Self::BufferLayouts => buffer_layouts::create_shader_module_embed_source(device),
    }
  }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
mod _root {
  pub use super::*;
  pub trait SetBindGroup {
    fn set_bind_group(
      &mut self,
      index: u32,
      bind_group: &wgpu::BindGroup,
      offsets: &[wgpu::DynamicOffset],
    );
  }
  impl SetBindGroup for wgpu::RenderPass<'_> {
    fn set_bind_group(
      &mut self,
      index: u32,
      bind_group: &wgpu::BindGroup,
      offsets: &[wgpu::DynamicOffset],
    ) {
      self.set_bind_group(index, bind_group, offsets);
    }
  }
  impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
    fn set_bind_group(
      &mut self,
      index: u32,
      bind_group: &wgpu::BindGroup,
      offsets: &[wgpu::DynamicOffset],
    ) {
      self.set_bind_group(index, bind_group, offsets);
    }
  }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod layout_asserts {
  use super::{_root, _root::*};
  const WGSL_BASE_TYPE_ASSERTS: () = {};
  const BUFFER_LAYOUTS_FIXED_LAYOUT_ASSERTS: () = {
    assert!(std::mem::offset_of!(buffer_layouts::FixedLayout, primary) == 0);
    assert!(std::mem::offset_of!(buffer_layouts::FixedLayout, accents) == 16);
    assert!(std::mem::offset_of!(buffer_layouts::FixedLayout, tag) == 48);
    assert!(std::mem::align_of::<buffer_layouts::FixedLayout>() == 16);
    assert!(std::mem::size_of::<buffer_layouts::FixedLayout>() == 64);
  };
  const BUFFER_LAYOUTS_RUNTIME_LAYOUT_ASSERTS: () = {
    assert!(std::mem::offset_of!(buffer_layouts::RuntimeLayoutSized<0>, header) == 0);
    assert!(std::mem::offset_of!(buffer_layouts::RuntimeLayoutSized<0>, colors) == 64);
    assert!(std::mem::align_of::<buffer_layouts::RuntimeLayoutSized<0>>() == 16);
    assert!(std::mem::size_of::<[f32; 4]>() == 16);
  };
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod buffer_layouts {
  use super::{_root, _root::*};
  #[repr(C, align(16))]
  #[derive(Debug, PartialEq, Clone, Copy)]
  pub struct FixedLayout {
    #[doc = "offset: 0, size: 12, type: `vec3<f32>`"]
    pub primary: [f32; 4],
    #[doc = "offset: 16, size: 32, type: `array<vec3<f32>, 2>`"]
    pub accents: [[f32; 4]; 2],
    #[doc = "offset: 48, size: 4, type: `u32`"]
    pub tag: u32,
    pub _pad_tag: [u8; 16 - ::core::mem::size_of::<u32>()],
  }
  impl FixedLayout {
    pub const fn new(primary: [f32; 4], accents: [[f32; 4]; 2], tag: u32) -> Self {
      Self {
        primary,
        accents,
        tag,
        _pad_tag: [0; 16 - ::core::mem::size_of::<u32>()],
      }
    }
  }
  #[repr(C)]
  #[derive(Debug, PartialEq, Clone, Copy)]
  pub struct FixedLayoutInit {
    pub primary: [f32; 4],
    pub accents: [[f32; 4]; 2],
    pub tag: u32,
  }
  impl FixedLayoutInit {
    pub fn build(&self) -> FixedLayout {
      FixedLayout {
        primary: self.primary,
        accents: self.accents,
        tag: self.tag,
        _pad_tag: [0; 16 - ::core::mem::size_of::<u32>()],
      }
    }
  }
  impl From<FixedLayoutInit> for FixedLayout {
    fn from(data: FixedLayoutInit) -> Self {
      data.build()
    }
  }
  #[repr(C, align(16))]
  #[derive(Debug, PartialEq, Clone, Copy)]
  pub struct RuntimeLayout<Tail = [[f32; 4]]>
  where
    Tail: WgslBindgenRuntimeArray<[f32; 4]> + ?Sized,
  {
    #[doc = "offset: 0, size: 64, type: `FixedLayout`"]
    pub header: FixedLayout,
    #[doc = "offset: 64, size: 16, type: `array<vec4<f32>>`"]
    pub colors: Tail,
  }
  pub type RuntimeLayoutSized<const N: usize> = RuntimeLayout<[[f32; 4]; N]>;
  impl<const N: usize> RuntimeLayoutSized<N> {
    pub const fn new_sized(header: FixedLayout, colors: [[f32; 4]; N]) -> Self {
      Self { header, colors }
    }
    pub fn as_bytes(&self) -> &[u8]
    where
      FixedLayout: bytemuck::Pod,
      [f32; 4]: bytemuck::Pod,
    {
      let __wgsl_bindgen_unsized: &RuntimeLayout = self;
      __wgsl_bindgen_unsized.as_bytes()
    }
  }
  impl RuntimeLayout {
    pub fn new(header: FixedLayout, colors: &[[f32; 4]]) -> Box<Self>
    where
      [f32; 4]: bytemuck::Pod,
    {
      use std::{alloc, mem, ptr};
      let __wgsl_bindgen_tail_offset = mem::offset_of!(RuntimeLayoutSized<0>, colors);
      let __wgsl_bindgen_tail_size = colors
        .len()
        .checked_mul(mem::size_of::<[f32; 4]>())
        .expect("runtime-sized struct allocation is too large");
      let __wgsl_bindgen_unpadded_size = __wgsl_bindgen_tail_offset
        .checked_add(__wgsl_bindgen_tail_size)
        .expect("runtime-sized struct allocation is too large");
      let __wgsl_bindgen_alignment = mem::align_of::<RuntimeLayoutSized<0>>();
      let __wgsl_bindgen_allocation_size = __wgsl_bindgen_unpadded_size
        .checked_add(__wgsl_bindgen_alignment - 1)
        .map(|size| size & !(__wgsl_bindgen_alignment - 1))
        .expect("runtime-sized struct allocation is too large");
      let __wgsl_bindgen_layout = alloc::Layout::from_size_align(
        __wgsl_bindgen_allocation_size,
        __wgsl_bindgen_alignment,
      )
      .expect("runtime-sized struct has an invalid allocation layout");
      unsafe {
        let __wgsl_bindgen_allocation = if __wgsl_bindgen_allocation_size == 0 {
          ptr::NonNull::<RuntimeLayoutSized<0>>::dangling()
            .as_ptr()
            .cast::<u8>()
        } else {
          let allocation = alloc::alloc(__wgsl_bindgen_layout);
          if allocation.is_null() {
            alloc::handle_alloc_error(__wgsl_bindgen_layout);
          }
          allocation
        };
        let __wgsl_bindgen_tail = ptr::slice_from_raw_parts_mut(
          __wgsl_bindgen_allocation.cast::<[f32; 4]>(),
          colors.len(),
        );
        let __wgsl_bindgen_this = __wgsl_bindgen_tail as *mut Self;
        ::core::ptr::addr_of_mut!((*__wgsl_bindgen_this).header).write(header);
        ptr::copy_nonoverlapping(
          colors.as_ptr(),
          ptr::addr_of_mut!((*__wgsl_bindgen_this).colors).cast::<[f32; 4]>(),
          colors.len(),
        );
        Box::from_raw(__wgsl_bindgen_this)
      }
    }
    pub fn as_bytes(&self) -> &[u8]
    where
      FixedLayout: bytemuck::Pod,
      [f32; 4]: bytemuck::Pod,
    {
      let __wgsl_bindgen_len = ::core::mem::offset_of!(RuntimeLayoutSized<0>, colors)
        + ::core::mem::size_of_val(&self.colors);
      unsafe {
        std::slice::from_raw_parts(self as *const Self as *const u8, __wgsl_bindgen_len)
      }
    }
  }
  #[doc(hidden)]
  mod __wgsl_bindgen_runtime_array_sealed {
    pub trait Sealed {}
    impl<T> Sealed for [T] {}
    impl<T, const N: usize> Sealed for [T; N] {}
  }
  #[doc(hidden)]
  pub trait WgslBindgenRuntimeArray<T>:
    __wgsl_bindgen_runtime_array_sealed::Sealed
  {
  }
  impl<T> WgslBindgenRuntimeArray<T> for [T] {}
  impl<T, const N: usize> WgslBindgenRuntimeArray<T> for [T; N] {}
  pub const ENTRY_VS_MAIN: &str = "vs_main";
  pub const ENTRY_FS_MAIN: &str = "fs_main";
  #[derive(Debug)]
  pub struct VertexEntry<const N: usize> {
    pub entry_point: &'static str,
    pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
    pub constants: Vec<(&'static str, f64)>,
  }
  pub fn vertex_state<'a, const N: usize>(
    module: &'a wgpu::ShaderModule,
    entry: &'a VertexEntry<N>,
  ) -> wgpu::VertexState<'a> {
    wgpu::VertexState {
      module,
      entry_point: Some(entry.entry_point),
      buffers: &entry.buffers,
      compilation_options: wgpu::PipelineCompilationOptions {
        constants: &entry.constants,
        ..Default::default()
      },
    }
  }
  pub fn vs_main_entry() -> VertexEntry<0> {
    VertexEntry {
      entry_point: ENTRY_VS_MAIN,
      buffers: [],
      constants: Default::default(),
    }
  }
  #[derive(Debug)]
  pub struct FragmentEntry<const N: usize> {
    pub entry_point: &'static str,
    pub targets: [Option<wgpu::ColorTargetState>; N],
    pub constants: Vec<(&'static str, f64)>,
  }
  pub fn fragment_state<'a, const N: usize>(
    module: &'a wgpu::ShaderModule,
    entry: &'a FragmentEntry<N>,
  ) -> wgpu::FragmentState<'a> {
    wgpu::FragmentState {
      module,
      entry_point: Some(entry.entry_point),
      targets: &entry.targets,
      compilation_options: wgpu::PipelineCompilationOptions {
        constants: &entry.constants,
        ..Default::default()
      },
    }
  }
  pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
    FragmentEntry {
      entry_point: ENTRY_FS_MAIN,
      targets,
      constants: Default::default(),
    }
  }
  #[derive(Debug)]
  pub struct WgpuBindGroup0EntriesParams<'a> {
    pub uniform_layout: wgpu::BufferBinding<'a>,
    pub direct_layout: wgpu::BufferBinding<'a>,
    pub layout_array: wgpu::BufferBinding<'a>,
    pub runtime_layout: wgpu::BufferBinding<'a>,
  }
  #[derive(Clone, Debug)]
  pub struct WgpuBindGroup0Entries<'a> {
    pub uniform_layout: wgpu::BindGroupEntry<'a>,
    pub direct_layout: wgpu::BindGroupEntry<'a>,
    pub layout_array: wgpu::BindGroupEntry<'a>,
    pub runtime_layout: wgpu::BindGroupEntry<'a>,
  }
  impl<'a> WgpuBindGroup0Entries<'a> {
    pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
      Self {
        uniform_layout: wgpu::BindGroupEntry {
          binding: 0,
          resource: wgpu::BindingResource::Buffer(params.uniform_layout),
        },
        direct_layout: wgpu::BindGroupEntry {
          binding: 1,
          resource: wgpu::BindingResource::Buffer(params.direct_layout),
        },
        layout_array: wgpu::BindGroupEntry {
          binding: 2,
          resource: wgpu::BindingResource::Buffer(params.layout_array),
        },
        runtime_layout: wgpu::BindGroupEntry {
          binding: 3,
          resource: wgpu::BindingResource::Buffer(params.runtime_layout),
        },
      }
    }
    pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 4] {
      [
        self.uniform_layout,
        self.direct_layout,
        self.layout_array,
        self.runtime_layout,
      ]
    }
    pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
      self.into_array().into_iter().collect()
    }
  }
  #[derive(Debug)]
  pub struct WgpuBindGroup0(wgpu::BindGroup);
  impl WgpuBindGroup0 {
    pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
      wgpu::BindGroupLayoutDescriptor {
        label: Some("BufferLayouts::BindGroup0::LayoutDescriptor"),
        entries: &[
          #[doc = " @binding(0): \"uniform_layout\""]
          wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
            ty: wgpu::BindingType::Buffer {
              ty: wgpu::BufferBindingType::Uniform,
              has_dynamic_offset: false,
              min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                _root::buffer_layouts::FixedLayout,
              >() as _),
            },
            count: None,
          },
          #[doc = " @binding(1): \"direct_layout\""]
          wgpu::BindGroupLayoutEntry {
            binding: 1,
            visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
            ty: wgpu::BindingType::Buffer {
              ty: wgpu::BufferBindingType::Storage { read_only: true },
              has_dynamic_offset: false,
              min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                _root::buffer_layouts::FixedLayout,
              >() as _),
            },
            count: None,
          },
          #[doc = " @binding(2): \"layout_array\""]
          wgpu::BindGroupLayoutEntry {
            binding: 2,
            visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
            ty: wgpu::BindingType::Buffer {
              ty: wgpu::BufferBindingType::Storage { read_only: true },
              has_dynamic_offset: false,
              min_binding_size: None,
            },
            count: None,
          },
          #[doc = " @binding(3): \"runtime_layout\""]
          wgpu::BindGroupLayoutEntry {
            binding: 3,
            visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
            ty: wgpu::BindingType::Buffer {
              ty: wgpu::BufferBindingType::Storage { read_only: true },
              has_dynamic_offset: false,
              min_binding_size: None,
            },
            count: None,
          },
        ],
      };
    pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
      device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
    }
    pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
      let bind_group_layout = Self::get_bind_group_layout(device);
      let entries = bindings.into_array();
      let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("BufferLayouts::BindGroup0"),
        layout: &bind_group_layout,
        entries: &entries,
      });
      Self(bind_group)
    }
    pub fn set(&self, pass: &mut impl SetBindGroup) {
      pass.set_bind_group(0, &self.0, &[]);
    }
  }
  #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
  #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
  #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
  #[doc = "   - Bind group 1: More frequent updates"]
  #[doc = "   - Bind group 2: More frequent updates"]
  #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
  #[derive(Debug, Copy, Clone)]
  pub struct WgpuBindGroups<'a> {
    pub bind_group0: &'a WgpuBindGroup0,
  }
  impl<'a> WgpuBindGroups<'a> {
    pub fn set(&self, pass: &mut impl SetBindGroup) {
      self.bind_group0.set(pass);
    }
  }
  #[derive(Debug)]
  pub struct WgpuPipelineLayout;
  impl WgpuPipelineLayout {
    pub fn bind_group_layout_entries(
      entries: [wgpu::BindGroupLayout; 1],
    ) -> [wgpu::BindGroupLayout; 1] {
      entries
    }
  }
  pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
    device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
      label: Some("BufferLayouts::PipelineLayout"),
      bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
      immediate_size: 0u32,
    })
  }
  pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
    let source = std::borrow::Cow::Borrowed(SHADER_STRING);
    device.create_shader_module(wgpu::ShaderModuleDescriptor {
      label: Some("buffer_layouts.wgsl"),
      source: wgpu::ShaderSource::Wgsl(source),
    })
  }
  pub const SHADER_STRING: &str = r#"
struct FixedLayout {
    primary: vec3<f32>,
    accents: array<vec3<f32>, 2>,
    tag: u32,
}

struct RuntimeLayout {
    header: FixedLayout,
    colors: array<vec4<f32>>,
}

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) uv: vec2<f32>,
}

@group(0) @binding(0) 
var<uniform> uniform_layout: FixedLayout;
@group(0) @binding(1) 
var<storage> direct_layout: FixedLayout;
@group(0) @binding(2) 
var<storage> layout_array: array<FixedLayout>;
@group(0) @binding(3) 
var<storage> runtime_layout: RuntimeLayout;

fn card(primary_1: vec3<f32>, accent_1: vec3<f32>, tag_1: u32, local: vec2<f32>) -> vec3<f32> {
    let edge = min(min(local.x, (1f - local.x)), min(local.y, (1f - local.y)));
    let inset = smoothstep(0.015f, 0.045f, edge);
    let glow = (0.85f + (0.15f * cos((((local.x + local.y) * 6.28318f) + f32(tag_1)))));
    return mix(vec3(0.025f), (mix(primary_1, accent_1, 0.22f) * glow), inset);
}

@vertex 
fn vs_main(@builtin(vertex_index) index: u32) -> VertexOutput {
    var output: VertexOutput;

    let positions = array<vec2<f32>, 3>(vec2<f32>(-1f, -1f), vec2<f32>(3f, -1f), vec2<f32>(-1f, 3f));
    output.position = vec4<f32>(positions[index], 0f, 1f);
    output.uv = ((positions[index] * vec2<f32>(0.5f, -0.5f)) + vec2(0.5f));
    let _e26 = output;
    return _e26;
}

@fragment 
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
    var primary: vec3<f32>;
    var accent: vec3<f32>;
    var tag: u32;

    let tile = min(vec2<u32>((input.uv * 2f)), vec2(1u));
    let local_1 = fract((input.uv * 2f));
    let tile_index = ((tile.y * 2u) + tile.x);
    switch tile_index {
        case 0u: {
            let _e19 = uniform_layout.primary;
            primary = _e19;
            let _e24 = uniform_layout.accents[0];
            accent = _e24;
            let _e28 = uniform_layout.tag;
            tag = _e28;
        }
        case 1u: {
            let _e32 = direct_layout.primary;
            primary = _e32;
            let _e36 = direct_layout.accents[1];
            accent = _e36;
            let _e39 = direct_layout.tag;
            tag = _e39;
        }
        case 2u: {
            let count = arrayLength((&layout_array));
            let item = min(u32((local_1.x * f32(count))), (count - 1u));
            let _e52 = layout_array[item].primary;
            primary = _e52;
            let _e59 = layout_array[item].accents[(item % 2u)];
            accent = _e59;
            let _e63 = layout_array[item].tag;
            tag = _e63;
        }
        default: {
            let count_1 = arrayLength((&runtime_layout.colors));
            let item_1 = min(u32((local_1.x * f32(count_1))), (count_1 - 1u));
            let _e77 = runtime_layout.colors[item_1];
            primary = _e77.xyz;
            let _e85 = runtime_layout.header.accents[(item_1 % 2u)];
            accent = _e85;
            let _e89 = runtime_layout.header.tag;
            tag = _e89;
        }
    }
    let _e90 = primary;
    let _e91 = accent;
    let _e92 = tag;
    let _e93 = card(_e90, _e91, _e92, local_1);
    return vec4<f32>(_e93, 1f);
}
"#;
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bytemuck_impls {
  use super::{_root, _root::*};
  unsafe impl bytemuck::Zeroable for buffer_layouts::FixedLayout {}
  unsafe impl bytemuck::Pod for buffer_layouts::FixedLayout {}
}
