name: wgsl_bindgen CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo +nightly clippy --features=validate,debug --workspace
    - name: Run tests
      run: cargo test --verbose
